const songs = {
  easy: [
    {   
      id: 100,
      title: "Guilty",
      artist: "Lady Wray",
      album: "Queen Alone",
      artistUrl: "https://open.spotify.com/artist/1plioVQ0mcgAO7uhvWkJJy",
      songUrl: "https://open.spotify.com/track/5ICdHl6m8XMMZbvAR3fylo",
      albumUrl: "https://open.spotify.com/album/4iJH23rAmDOdapyI9DFRd8?si=ljXVFFtgTGipXDZjbP-AoQ",
      fileName: ["https://f000.backblazeb2.com/file/soundpuzzles/guilty_final_chorus.m4a"],
      mbid: '7a0813ca-4712-46be-9f4b-929ea0382726',
      coverImg: "https://f000.backblazeb2.com/file/soundpuzzles/album-covers/guilty.jpg",
      colorPalette: ['#104947', '#eb7fa7', '#ed6382', '#a16472', '#616272', '#526156', '#573229', '#ab282c', '#e93a45'],
      difficulty: "easy",
      numSnippets: 4,
      snippetSecondsLength: 2,
      isSolved: false
    },
    {
      id: 101,
      title: "All Apologies",
      artist: "Iron Horse",
      album: "Pickin' On Nirvana",
      artistUrl: "https://open.spotify.com/artist/1v3CnxHAtLMfZW8v5dGj7t?si=VfMUkeM8TIuvggG_mKrjrw",
      songUrl: "https://open.spotify.com/track/2V20qEDlwFlpTZsvL5TqgS?si=4VPWPY_vSQ2GyniiMCnBeQ",
      albumUrl: "https://open.spotify.com/album/40uCxIjfM2ixXThi8SHwdF?si=SmQaZe-cSS-sVRwZ_In2yg",
      fileName: ["https://f000.backblazeb2.com/file/soundpuzzles/all-apologies-first-verse.m4a"],
      coverImg: "https://f000.backblazeb2.com/file/soundpuzzles/album-covers/all-apologies.jpg",
      colorPalette: ["#F2F2F0","#3E3526","#71675A","#BDB4A6","#271C14"],
      difficulty: "easy",
      numSnippets: 4,
      snippetSecondsLength: 2.8,
      isSolved: false
    },
    {
      id: 102,
      title: "Bette Davis Eyes",
      artist: "Kim Carnes",
      album: "Mistaken Identity",
      artistUrl: "https://open.spotify.com/artist/5PN2aHIvLEM98XIorsPMhE",
      songUrl: "https://open.spotify.com/track/0odIT9B9BvOCnXfS0e4lB5",
      albumUrl: "https://open.spotify.com/album/3iMwQk5yE0UDDKbLCdcxZA?si=RomGCGraTTiy5y8RFJz-KA",
      fileName: ["https://f000.backblazeb2.com/file/soundpuzzles/bette_davis_eyes_first_verse.m4a"],
      coverImg: "https://f000.backblazeb2.com/file/soundpuzzles/album-covers/bette-davis-eyes.jpg",
      colorPalette: ["#19150b","#655c3c","#e38d6f","#5c2909","#af6f12","#86470d","#a46a59","#728667","#a67633","#dfd2ae"],
      difficulty: "easy",
      numSnippets: 4,
      snippetSecondsLength: 4.22,
      isSolved: false
    }
  ],
  medium: [
    {
      id: 200,
      title: "River",
      artist: "Leon Bridges",
      album: "Coming Home",
      artistUrl: "https://open.spotify.com/artist/3qnGvpP8Yth1AqSBMqON5x",
      songUrl: "https://open.spotify.com/track/0NeJjNlprGfZpeX2LQuN6c",
      albumUrl: "https://open.spotify.com/album/4svLfrPPk2npPVuI4kXPYg?si=Cati1U4XQ5KLrK6Bb0D0Ig",
      fileName: ["https://f000.backblazeb2.com/file/soundpuzzles/river_chorus.m4a"],
      difficulty: "medium",
      numSnippets: 7,
      coverImg: "https://f000.backblazeb2.com/file/soundpuzzles/album-covers/river.jpg",
      colorPalette: ['#8c0726','#a50a2a','#750123','#312528','#be6b73','#d19ea5','#75666e','#5f1327', '#e4cfc4'],
      snippetSecondsLength: 1.75,
      isSolved: false
    },
    {
      id: 201,
      title: "He Called Me Baby",
      artist: "Candi Staton",
      album: "Coming Home",
      artistUrl: "https://open.spotify.com/artist/3S34Unhn5yRcaH5K9aU5Et",
      songUrl: "https://open.spotify.com/track/3zIiZrCROmhS9ERPdEHXYa",
      albumUrl: "https://open.spotify.com/album/5FSETqzUj1EAlIVvPYmv5r",
      fileName: ["https://f000.backblazeb2.com/file/soundpuzzles/he-called-me-baby-last-verse.m4a"],
      difficulty: "medium",
      numSnippets: 7,
      coverImg: "https://f000.backblazeb2.com/file/soundpuzzles/album-covers/he-called-me-baby.jpg",
      colorPalette: ["#150e84","#160a06","#ad9b72","#ea2a1a","#ac86a1","#dfaba2","#55226f","#965220","#913959","#aa1e38"],
      snippetSecondsLength: 1.5,
      isSolved: false
    },
    {
      id: 202,
      title: "At The River",
      artist: "Groove Armada",
      album: "Vertigo",
      artistUrl: "https://open.spotify.com/artist/67tgMwUfnmqzYsNAtnP6YJ?si=hgSURQxWSEqxZpCb6tN82w",
      songUrl: "https://open.spotify.com/track/0KIPa0YuQ5QFmlAqRyXNd9?si=EAOQ_ZB9Q7qkX_05OiqzDQ",
      albumUrl: "https://open.spotify.com/album/1KzGIlZIlhRwUIoPlexdax?si=sVQtwEECTsSpVj1yrn6OgQ",
      fileName: ["https://f000.backblazeb2.com/file/soundpuzzles/at-the-river-last-chorus-short.m4a"],
      difficulty: "medium",
      numSnippets: 7,
      coverImg: "https://f000.backblazeb2.com/file/soundpuzzles/album-covers/at-the-river.jpg",
      colorPalette: ["rgb(56, 69, 90)", "rgb(133, 181, 193)", "rgb(54, 113, 139)", "rgb(44, 112, 116)", "rgb(244, 244, 244)", "rgb(25, 61, 43)", "rgb(42, 53, 26)"],
      snippetSecondsLength: 2.07,
      isSolved: false
    }
  ],
  hard: [
    {
      id: 300,
      title: "Vitamin C",
      artist: "Can",
      album: "Ege Bamyasi",
      artistUrl: "https://open.spotify.com/artist/4l8xPGtl6DHR2uvunqrl8r",
      songUrl: "https://open.spotify.com/track/1tzXnPndBrd2G5GXrOBc1c",
      albumUrl: "https://open.spotify.com/album/3Qa2CdymyGvXkqoqIZykmT?si=h1Ca4WVbTA6BXXmIww_CGg",
      fileName: ["https://f000.backblazeb2.com/file/soundpuzzles/vitamin_c_chorus_shorter.m4a"],
      coverImg: "https://f000.backblazeb2.com/file/soundpuzzles/album-covers/can.jpg",
      colorPalette: ['#0e0b19', '#77a821', '#52782d','#8dad8e','#b1b119','#f0f4f0','#182f10','#c06326','#e8972c','#354747', '#f3f3f1'],
      difficulty: "hard",
      numSnippets: 12,
      snippetSecondsLength: 1,
      isSolved: false
    },
    {
      id: 301,
      title: "Suicide",
      artist: "Midnight to Monaco",
      album: "Suicide",
      artistUrl: "https://open.spotify.com/artist/3S81oM6w9tzFUxEzvdql6I",
      songUrl: "https://open.spotify.com/track/0FfkP3Ta4kYMlKuzaZhvEc",
      albumUrl: "https://open.spotify.com/album/6jPdW0gQlWL08om0o4WO9L",
      fileName: ["https://f000.backblazeb2.com/file/soundpuzzles/suicide-start.m4a"],
      difficulty: "hard",
      numSnippets: 12,
      coverImg: "https://f000.backblazeb2.com/file/soundpuzzles/album-covers/suicide.jpg",
      colorPalette: ["#3F080F","#002223","#456C6A","#C09650","#5B4E3B","#ff530d","#d9d7d3"],
      snippetSecondsLength: 3.3,
      isSolved: false
    },
        {
      id: 302,
      title: "A Moment Apart",
      artist: "ODESZA",
      album: "A Moment Apart",
      artistUrl: "https://open.spotify.com/artist/21mKp7DqtSNHhCAU2ugvUw?si=wRo661_ASYy0OmnNgIR1bA",
      songUrl: "https://open.spotify.com/track/59wlTaYOL5tDUgXnbBQ3my?si=NixIHdTpQnqDgAfnMQgeWA",
      albumUrl: "https://open.spotify.com/album/3VzsvmhnUb9OZ59bq2aoNZ?si=UYz3AuyvQ2eald5suKv0ag",
      fileName: ["https://f000.backblazeb2.com/file/soundpuzzles/a-moment-apart-end.m4a"],
      difficulty: "hard",
      numSnippets: 10,
      coverImg: "https://f000.backblazeb2.com/file/soundpuzzles/album-covers/a-moment-apart.jpg",
      colorPalette: ["rgb(22, 82, 113)", "rgb(14, 69, 86)","rgb(67, 145, 167)","rgb(241, 207, 140)","rgb(139, 63, 34)","rgb(10, 14, 14)","rgb(238, 178, 151)","rgb(38, 75, 6)","rgb(138, 121, 141)","rgb(225, 225, 225)","rgb(246, 221, 146)","rgb(34, 36, 32)"],
      snippetSecondsLength: 2,
      isSolved: false
    }
  ]
};

export default songs;